CREATE DATABASE JAVA;

USE JAVA;

CREATE TABLE ACCOUNTS(
	USERNAME	VARCHAR(16)		PRIMARY KEY	,
    HASHPASS	VARCHAR(60)					,
    EMAIL		VARCHAR(60)		UNIQUE
);

CREATE TABLE APPOINTMENTS (
	EID			INT			AUTO_INCREMENT	,
    EUSERNAME	VARCHAR(16)					,
    ENAME		VARCHAR(60)		NOT NULL	,
    ELOCATION	VARCHAR(60)					,
    EDURATION	INT				NOT NULL	,
    EDAY		INT				NOT NULL	,
    EMONTH		INT				NOT NULL	,
    EYEAR		INT				NOT NULL	,
    EHOUR		INT				NOT NULL	,
    EMINUTE		INT				NOT NULL	,
    EPRIORITY	ENUM('1', '2', '3')			,
    PRIMARY KEY(EID),
    FOREIGN KEY (EUSERNAME) REFERENCES ACCOUNTS (USERNAME) ON DELETE CASCADE
);

CREATE TABLE PARTICIPANTS (
	PID			INT 						,
	PEMAIL		VARCHAR(60)					,
    PTIME		INT							,
    PRIMARY KEY (PEMAIL, PID)				,
    FOREIGN KEY (PID) REFERENCES APPOINTMENTS (EID)	ON DELETE CASCADE
);

